version: '3.8'

services:
  db:
    image: debezium/postgres:16
    container_name: vmaster-backend-database
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: "UTC"
    ports:
      - "${DATABASE_PORT}:5432"
    mem_limit: 4g
    cpus: "2.0"
    networks:
      - inventory
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: "False"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    networks:
      - inventory

volumes:
  postgres_data:
  pgadmin_data:

networks:
  inventory:
    driver: bridge